# Generated by Django 2.0 on 2018-01-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20170805_1700'),
        ('gameplay', '0003_auto_20180122_0943'),
        ('gameplay', '0003_auto_20170606_1314'),
    ]

    operations = [
    ]
